name = "ryden-core"
main = "src/index.ts"
compatibility_date = "2026-01-30"

[vars]
OPENROUTER_MODEL = "google/gemini-2.0-flash-lite-preview-02-05:free"

[[d1_databases]]
binding = "DB"
database_name = "ryden_db"
database_id = "041747db-997f-499b-8b64-e79c51405f1d"
